import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
} from "next/font/google";
import "./globals.css";
import { Header } from "./components/header/header";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#fbfbfb] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white shadow-[0_29px_39px_0_rgba(0,0,0,0.01)]">
          <Header />
        </header>

        {children}
      </body>
    </html>
  );
}
